import React from 'react';
import Pill from '../Pill';

import { classnames } from '../../lib';
const pillColors = {
  Carpentry: 'bg-red-700',
  Plumbing: 'bg-blue-700',
  'Electrical Work': 'bg-green-700',
  'HVAC Services': 'bg-purple-700',
  Landscaping: 'bg-yellow-700',
  Masonry: 'bg-teal-700',
  Painting: 'bg-orange-700',
  'Construction Labor': 'bg-indigo-700',
  Roofing: 'bg-gray-700',
  Welding: 'bg-pink-700',
  'Flooring Installation': 'bg-red-800',
  Tiling: 'bg-blue-800',
  'Window Installation': 'bg-green-800',
  'Door Installation': 'bg-purple-800',
  'Drywall Installation': 'bg-yellow-800',
  Demolition: 'bg-teal-800',
  'Home Inspection': 'bg-orange-800',
  'Security System Installation': 'bg-indigo-800',
  'Pest Control': 'bg-gray-800',
  'Cleaning Services': 'bg-pink-800',
  'Janitorial Services': 'bg-red-900',
  'Moving Services': 'bg-blue-900',
  'Event Setup & Tear Down': 'bg-green-900',
  Catering: 'bg-purple-900',
  Bartending: 'bg-yellow-900',
  'DJ Services': 'bg-teal-900',
  Photography: 'bg-orange-900',
  Videography: 'bg-indigo-900',
  'Stage Lighting Setup': 'bg-gray-900',
  'Sound System Setup': 'bg-pink-900',
  'Furniture Assembly': 'bg-red-600',
  'Handyman Services': 'bg-blue-600',
  'Pool Maintenance': 'bg-green-600',
  'Appliance Repair': 'bg-purple-600',
  'Automotive Repair': 'bg-yellow-600',
  'Courier Services': 'bg-teal-600',
  'Personal Shopping': 'bg-orange-600',
  'Home Staging': 'bg-indigo-600',
  'Interior Decorating': 'bg-gray-600',
  'Pet Grooming': 'bg-pink-600',
  'Pet Sitting': 'bg-red-500',
  'Dog Walking': 'bg-blue-500',
  Childcare: 'bg-green-500',
  'Elderly Care': 'bg-purple-500',
  Tutoring: 'bg-yellow-500',
  'Fitness Training': 'bg-teal-500',
  'Massage Therapy': 'bg-orange-500',
  'Hair Styling': 'bg-indigo-500',
  'Makeup Artistry': 'bg-gray-500',
  'Nail Care': 'bg-pink-500',
  'Facial Treatments': 'bg-red-400',
  'Web Development': 'bg-blue-400',
  'Graphic Design': 'bg-green-400',
  'Content Writing': 'bg-purple-400',
  'Digital Marketing': 'bg-yellow-400',
  SEO: 'bg-teal-400',
  'Social Media Management': 'bg-orange-400',
  'Data Entry': 'bg-indigo-400',
  'Customer Service': 'bg-gray-400',
  'Virtual Assistance': 'bg-pink-400',
  'Mobile App Development': 'bg-red-300',
  'UI/UX Design': 'bg-blue-300',
  'Software Development': 'bg-green-300',
  'Video Editing': 'bg-purple-300',
  Translation: 'bg-yellow-300',
  Illustration: 'bg-teal-300',
  '3D Modeling': 'bg-orange-300',
  Animation: 'bg-indigo-300',
  Copywriting: 'bg-gray-300',
  Accounting: 'bg-pink-300',
  Bookkeeping: 'bg-red-200',
  Consulting: 'bg-blue-200',
  'Legal Services': 'bg-green-200',
  'Marketing Strategy': 'bg-purple-200',
  Sales: 'bg-yellow-200',
  'Business Development': 'bg-teal-200',
  'Project Management': 'bg-orange-200',
  'IT Support': 'bg-indigo-200',
  'Network Administration': 'bg-gray-200',
  'System Administration': 'bg-pink-200',
  'Game Development': 'bg-red-100',
  'E-commerce Development': 'bg-blue-100',
  'Email Marketing': 'bg-green-100',
  Branding: 'bg-purple-100',
  'Public Relations': 'bg-yellow-100',
  'Market Research': 'bg-teal-100',
  'Lead Generation': 'bg-orange-100',
  'Data Analysis': 'bg-indigo-100',
  'Machine Learning': 'bg-gray-100',
  'Artificial Intelligence': 'bg-pink-100',
  'Cloud Computing': 'bg-red-50',
  Cybersecurity: 'bg-blue-50',
  DevOps: 'bg-green-50',
  'Technical Writing': 'bg-purple-50',
  Research: 'bg-yellow-50',
  'Editing & Proofreading': 'bg-teal-50',
  Transcription: 'bg-orange-50',
  'Voice Over': 'bg-indigo-50',
  'Audio Production': 'bg-gray-50',
  'Music Production': 'bg-pink-50',
  'CAD Design': 'bg-red-400',
  Engineering: 'bg-blue-400',
  Architecture: 'bg-green-400',
  'Interior Design': 'bg-purple-400',
  'Fashion Design': 'bg-yellow-400',
  'Event Planning': 'bg-teal-400',
  'Personal Training': 'bg-orange-400',
  'Life Coaching': 'bg-indigo-400',
  'Health & Wellness': 'bg-gray-400',
  Fitness: 'bg-pink-400',
  Nutrition: 'bg-red-300',
  'Education & Tutoring': 'bg-blue-300',
  'Language Instruction': 'bg-green-300',
};

const JobCardPill = ({ name }) => {
  const bgColor = pillColors?.[name]?.toString();
  return (
    <div className="flex items-center  rounded-full">
      <Pill className={classnames(`${bgColor} text-white`)}>{name}</Pill>
    </div>
  );
};

export default JobCardPill;
